name: f_exam
description: Special Project for PDP University exam system

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  glassmorphism: ^3.0.0
  file_picker: ^5.3.3
  firebase_storage: ^11.2.6
  firebase_core: ^2.15.1
  lottie: ^2.6.0
  firebase_auth: ^4.8.0
  html: ^0.15.4
  flip_board: ^1.0.0
  intl: ^0.18.1
  firebase_database: ^10.2.5
  shared_preferences: ^2.2.0
  flip_card: ^0.7.0
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
